version: '3'
services:
  tumaguro-nest-db:
    container_name: tumaguro-nest-db
    image: postgres:14
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  tumaguro-nest-api:
    build: .
    volumes:
      - .:/opt
    ports:
      - '8000:3000'
    depends_on:
      - tumaguro-nest-db

  tumaguro-nest-adminer:
    container_name: tumaguro-nest-adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - tumaguro-nest-db

volumes:
  dbdata: null